package com.example.exercises;

interface Machine extends ColorPrinter, ColorCopyMachine, SmartScanner, Fax { // Contract <- SRP, Fat Interface
}

interface BlackPrinter {
	void print();
}

interface ColorPrinter extends BlackPrinter {
	void printColor();
}

interface Fax {
	void sendFax();

	void receiveFax();
}

interface BlackCopyMachine {
	void copy();
}

interface ColorCopyMachine extends BlackCopyMachine {
	void colorCopy();
}

interface StandardScanner {
	void scan();
}

interface SmartScanner extends StandardScanner {
	void scanAndEmail();

	void scanToUsbDevice();

	void scanToGoogleDrive();
}

class SimplePrinter implements BlackPrinter, StandardScanner {

	@Override
	public void print() {
		System.out.println("Printing black...");
	}

	@Override
	public void scan() {
		System.out.println("Scanning black...");
	}

}

class OfficePrinter implements Machine {

	@Override
	public void print() {
		System.out.println("Printing...");
	}

	@Override
	public void scan() {
		System.out.println("Scanning...");
	}

	@Override
	public void copy() {
		System.out.println("Copying...");
	}


	@Override
	public void scanAndEmail() {
		System.out.println("scanAndEmail...");
	}

	@Override
	public void scanToUsbDevice() {
		System.out.println("scanToUsbDevice...");
	}

	@Override
	public void scanToGoogleDrive() {
		System.out.println("scanToGoogleDrive...");
	}

	@Override
	public void printColor() {
		System.out.println("printColor...");
	}

	@Override
	public void colorCopy() {
		System.out.println("colorCopy...");
	}

	@Override
	public void sendFax() {
		System.out.println("sendFax...");
	}

	@Override
	public void receiveFax() {
		System.out.println("receiveFax...");
	}

}

public class Exercise04 {

	public static void main(String[] args) {
		var officePrinter = new OfficePrinter();
		ColorPrinter colorPrinter = officePrinter;
		colorPrinter.printColor();
		var _ = new SimplePrinter();
		useGenAIAndColorPrint("my prompt1",officePrinter);
		// useGenAIAndColorPrint("my prompt 2",simplePrinter);
	}

	public static void useGenAIAndColorPrint(String prompt,ColorPrinter colorPrinter) {
		var _ = "an image generated by ...";
		colorPrinter.printColor();
	}
}
